Updated Home Page
UncountedDeaths/UncountedDeaths pull request #63
Opened 2022-06-24 14:12 UTC by IanSaucy

2022-06-24 16:00 UTC, Aykerimm commented
Sure ,no problem 
> @Aykerimm Can you put the "What we do" below the iframe embed?

2022-06-24 20:03 UTC, toucham requested changes
small changes

2022-06-24 20:03 UTC, toucham commented on src/pages/MasterPage.tsx
>            <Route path={InternalRoutes.RESOURCES.path} element={<ResourcesPage />}></Route>
same as suggested above:
`<Route ... />`

2022-06-29 06:55 UTC, Aykerimm commented
I am trying to merge the changes from react_transfer branch. Should I change the death tracker app from RshinyApp to Tableau to be on the main page?

2022-07-01 14:50 UTC, merged