Updated dashboards on landing page
UncountedDeaths/UncountedDeaths pull request #90
Opened 2022-07-30 16:56 UTC by Aykerimm

- Added new dashboard style
 - Updated codebase to split landing page and dashboards
 - Added new maps and how they are shown
 - Added selector for data type on State dashboard
 - Fixed selector on County dashboard to be more flexible to use

2022-08-02 21:00 UTC, IanSaucy requested changes
Great work! Just a few changes.

2022-08-02 21:00 UTC, IanSaucy commented on src/components/nationalDashboard.tsx
> +    }
This is fine for now but can you put a to-do here to replace this with a `map`? Also, create an issue on Trello

2022-08-03 16:14 UTC, toucham requested changes

2022-08-03 16:14 UTC, toucham commented on src/components/countyDashboard.tsx
> +  };
isn't currCountry of type `string` not `CountyName`?

2022-08-03 16:14 UTC, toucham commented on src/components/countyDashboard.tsx
> +  const countiesDashboardURL = 'https://datawrapper.dwcdn.net/EviBb/2/';
use useState

2022-08-03 16:14 UTC, toucham commented on src/components/nationalDashboard.tsx
> +import { DataSourceType, dataSources } from '../content/NationalDashboard';
since `NationalDashboard` is not a component, it is better to keep it lower case `nationalDashboard`

2022-08-03 16:14 UTC, toucham commented on src/components/countyDashboard.tsx
> +            value={currCounty as CountyName}
```suggestion
            value={currCounty}
```

2022-08-03 16:14 UTC, toucham commented on src/components/nationalDashboard.tsx
> +  const [dataType, setDataType] = useState(dataSources[0]);
```suggestion
  const [dataType, setDataType] = useState<DataSourceType>(dataSources[0]);
```

2022-08-03 16:14 UTC, toucham commented on src/components/nationalDashboard.tsx
> +    }
```suggestion
    for (let i = 0; i < dataSources.length; i++) {
      if (dataSources[i].id === dataType) {
        setDataType(dataSources[i])
        break;
      }
    }
```

2022-08-04 01:23 UTC, Aykerimm commented on src/components/countyDashboard.tsx
> +  const countiesDashboardURL = 'https://datawrapper.dwcdn.net/EviBb/2/';
I did not have enough how to update those variables, so set them to static URLs. I will change them to state vars.

2022-08-04 01:25 UTC, IanSaucy commented
You could use state vars and set the default value to those URLS actually.
Should accomplish both!

On Wed, Aug 3, 2022, 5:23 PM Aigerim Dussikenova ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/components/countyDashboard.tsx
> <https://github.com/UncountedDeaths/UncountedDeaths/pull/90#discussion_r937267450>
> :
>
> > +  const stateCountiesDashboardURL = 'https://datawrapper.dwcdn.net/q9LZ6/3/';
> +  // should change when currCounty is updated. Shows map of a county
> +  const countiesDashboardURL = 'https://datawrapper.dwcdn.net/EviBb/2/';
>
> I did not have enough how to update those variables, so set them to static
> URLs. I will change them to state vars.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/UncountedDeaths/UncountedDeaths/pull/90#discussion_r937267450>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHMM7LNJN7B4IYUNTRCUBU3VXMLQZANCNFSM55DPU7TA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-08-04 02:19 UTC, Aykerimm commented
Couldn't get rid of `as` as it started complaining about `string[]` is not assignable to `CountyName[]` type for arrays and similar for singular items too.

2022-08-04 04:32 UTC, closed without merging